import type { Question, QuestionOption } from '@/types';

/**
 * Skala Likert standar untuk seluruh pertanyaan assessment.
 * Deskripsi dapat di-override per pertanyaan bila diperlukan konteks khusus.
 */
const likert = (descriptions?: [string, string, string, string]): QuestionOption[] => [
  {
    value: 0,
    label: 'Belum ada / Tidak diketahui',
    description: descriptions?.[0] ?? 'Tidak ada inisiatif maupun kesadaran terkait kontrol ini.',
  },
  {
    value: 1,
    label: 'Dalam perencanaan / Sebagian kecil diimplementasikan',
    description: descriptions?.[1] ?? 'Inisiatif sudah dimulai namun cakupan masih sangat terbatas.',
  },
  {
    value: 2,
    label: 'Sebagian besar diimplementasikan / Belum terdokumentasi',
    description: descriptions?.[2] ?? 'Kontrol berjalan di mayoritas proses namun belum formal/terdokumentasi.',
  },
  {
    value: 3,
    label: 'Fully implemented, terdokumentasi, dan diuji secara berkala',
    description: descriptions?.[3] ?? 'Kontrol matang: terdokumentasi, dievaluasi, dan diuji rutin.',
  },
];

export const QUESTIONS: Question[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 1 — TATA KELOLA & KEBIJAKAN (Pasal 20-26) — 10 pertanyaan
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'gov-01',
    domainId: 'governance',
    pasalRef: 'Pasal 20 Ayat 1',
    question:
      'Apakah organisasi telah menetapkan kebijakan tertulis terkait pelindungan data pribadi yang disahkan oleh manajemen?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 20 menetapkan kewajiban Pengendali Data Pribadi untuk memastikan pemrosesan sesuai prinsip pelindungan data. Kebijakan tertulis yang disahkan manajemen adalah bukti akuntabilitas paling mendasar.',
    evidenceRequired: true,
  },
  {
    id: 'gov-02',
    domainId: 'governance',
    pasalRef: 'Pasal 24',
    question:
      'Apakah terdapat prosedur penanganan pelanggaran data (data breach response plan) yang terdokumentasi dan dapat dieksekusi?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 24 mewajibkan Pengendali Data melakukan pemrosesan secara akuntabel. Breach response plan yang teruji memastikan organisasi mampu memenuhi kewajiban notifikasi 3x24 jam (Pasal 46).',
    evidenceRequired: true,
  },
  {
    id: 'gov-03',
    domainId: 'governance',
    pasalRef: 'Pasal 22',
    question: 'Apakah kebijakan retensi data telah didefinisikan dan diimplementasikan untuk setiap kategori data pribadi?',
    weight: 2,
    options: likert(),
    hint: 'UU PDP menganut prinsip pembatasan penyimpanan: data pribadi hanya disimpan selama diperlukan. Jadwal retensi per kategori data adalah implementasi praktisnya.',
    evidenceRequired: true,
  },
  {
    id: 'gov-04',
    domainId: 'governance',
    pasalRef: 'Pasal 21',
    question:
      'Apakah terdapat inventaris/register aset data pribadi (Record of Processing Activities) yang dikelola dan diperbarui organisasi?',
    weight: 3,
    options: likert(),
    hint: 'Tanpa inventaris data (RoPA), organisasi tidak dapat membuktikan dasar pemrosesan setiap data sebagaimana dituntut Pasal 20-21. Ini adalah prasyarat hampir semua kontrol kepatuhan lain.',
    evidenceRequired: true,
  },
  {
    id: 'gov-05',
    domainId: 'governance',
    pasalRef: 'Pasal 53-54',
    question: 'Apakah DPO (Data Protection Officer / Pejabat Pelindungan Data Pribadi) telah ditunjuk secara formal?',
    weight: 3,
    options: likert([
      'Belum ada penunjukan DPO sama sekali.',
      'Kandidat DPO sedang diidentifikasi atau merangkap tanpa SK formal.',
      'DPO aktif menjalankan fungsi namun SK/uraian tugas belum lengkap.',
      'DPO ditunjuk dengan SK resmi, independen, dan melapor ke pimpinan tertinggi.',
    ]),
    hint: 'Pasal 53-54 mewajibkan penunjukan pejabat/petugas pelindungan data pribadi bagi organisasi yang memproses data skala besar, data spesifik, atau untuk pelayanan publik.',
    evidenceRequired: true,
  },
  {
    id: 'gov-06',
    domainId: 'governance',
    pasalRef: 'Pasal 20 Ayat 2',
    question: 'Apakah peran dan tanggung jawab pengelolaan data pribadi telah didokumentasikan (RACI/struktur organisasi privasi)?',
    weight: 2,
    options: likert(),
    hint: 'Akuntabilitas menuntut kejelasan siapa Pengendali, siapa Prosesor, dan siapa penanggung jawab tiap aktivitas pemrosesan. Matriks RACI privasi adalah praktik umum untuk memenuhinya.',
    evidenceRequired: false,
  },
  {
    id: 'gov-07',
    domainId: 'governance',
    pasalRef: 'Pasal 26',
    question: 'Apakah kebijakan privasi (privacy notice) tersedia, mudah diakses, dan dipahami oleh subjek data?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 26 menjamin hak subjek data mendapatkan informasi yang jelas tentang identitas pengendali, dasar hukum, tujuan, dan akuntabilitas pemrosesan. Privacy notice adalah kanal utamanya.',
    evidenceRequired: true,
  },
  {
    id: 'gov-08',
    domainId: 'governance',
    pasalRef: 'Pasal 22',
    question: 'Apakah kebijakan data retention mempertimbangkan ketentuan minimum penyimpanan dari regulasi sektoral (perpajakan, perbankan, ketenagakerjaan)?',
    weight: 1,
    options: likert(),
    hint: 'Retensi data harus menyeimbangkan prinsip pembatasan penyimpanan UU PDP dengan kewajiban retensi minimum regulasi sektoral (mis. 10 tahun untuk dokumen perpajakan).',
    evidenceRequired: false,
  },
  {
    id: 'gov-09',
    domainId: 'governance',
    pasalRef: 'Pasal 43-44',
    question: 'Apakah terdapat prosedur penghapusan dan pemusnahan data pribadi saat data tidak lagi diperlukan?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 43-44 mengatur kewajiban penghapusan dan pemusnahan data pribadi. Prosedur harus mencakup data di sistem produksi, backup, dan arsip fisik, dengan berita acara pemusnahan.',
    evidenceRequired: true,
  },
  {
    id: 'gov-10',
    domainId: 'governance',
    pasalRef: 'Pasal 20 & 24',
    question: 'Apakah persetujuan (consent) subjek data didokumentasikan dengan baik, termasuk waktu, cakupan, dan mekanisme pemberiannya?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 20 jo. Pasal 24: pengendali wajib dapat membuktikan bahwa consent telah diberikan secara sah — eksplisit, terinformasi, dan terdokumentasi. Consent record adalah alat buktinya.',
    evidenceRequired: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 2 — HAK SUBJEK DATA (Pasal 5-16) — 10 pertanyaan
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'sr-01',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 7',
    question: 'Apakah tersedia mekanisme formal bagi subjek data untuk mengajukan permintaan akses terhadap data pribadinya?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 7 menjamin hak subjek data mendapatkan akses dan salinan data pribadinya. Organisasi perlu kanal permintaan (DSAR portal/email/form) dengan alur kerja yang jelas.',
    evidenceRequired: true,
  },
  {
    id: 'sr-02',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 8',
    question: 'Apakah terdapat prosedur pemenuhan hak penghapusan data (right to erasure) yang mencakup seluruh sistem penyimpanan?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 8 memberi hak kepada subjek data untuk mengakhiri pemrosesan dan menghapus data pribadinya. Penghapusan harus efektif di database produksi, backup, dan sistem pihak ketiga.',
    evidenceRequired: true,
  },
  {
    id: 'sr-03',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 13',
    question: 'Apakah terdapat SLA respons yang terdefinisi untuk permintaan portabilitas data subjek?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 13 menjamin hak subjek data mendapatkan dan menggunakan data pribadinya dalam format yang lazim digunakan (interoperable). SLA respons memastikan hak ini dipenuhi tepat waktu.',
    evidenceRequired: false,
  },
  {
    id: 'sr-04',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 9',
    question: 'Apakah tersedia mekanisme penarikan kembali persetujuan (withdraw consent) yang semudah saat consent diberikan?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 9 menjamin hak menarik kembali persetujuan pemrosesan. Best practice global: proses penarikan tidak boleh lebih sulit daripada proses pemberian consent.',
    evidenceRequired: true,
  },
  {
    id: 'sr-05',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 10',
    question: 'Apakah terdapat prosedur penanganan keberatan subjek data atas pemrosesan, termasuk pengambilan keputusan otomatis (automated decision-making)?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 10 menjamin hak mengajukan keberatan atas pengambilan keputusan yang hanya didasarkan pada pemrosesan otomatis, termasuk pemrofilan (profiling) yang menimbulkan akibat hukum.',
    evidenceRequired: false,
  },
  {
    id: 'sr-06',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 7 & 32',
    question: 'Apakah dilakukan verifikasi identitas pemohon sebelum pemenuhan permintaan hak subjek data?',
    weight: 3,
    options: likert(),
    hint: 'Tanpa verifikasi identitas, pemenuhan DSAR justru bisa menjadi kebocoran data — menyerahkan data pribadi kepada pihak yang tidak berhak. Verifikasi proporsional adalah kontrol wajib.',
    evidenceRequired: false,
  },
  {
    id: 'sr-07',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 6',
    question: 'Apakah subjek data dapat meminta perbaikan/pembaruan (rektifikasi) data pribadinya yang tidak akurat?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 6 menjamin hak melengkapi, memperbarui, dan memperbaiki data pribadi. Mekanisme rektifikasi harus tersedia dan perubahan dipropagasikan ke seluruh sistem terkait.',
    evidenceRequired: false,
  },
  {
    id: 'sr-08',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 11',
    question: 'Apakah terdapat mekanisme bagi subjek data untuk menunda atau membatasi pemrosesan data pribadinya?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 11 menjamin hak menunda atau membatasi pemrosesan secara proporsional. Sistem perlu mendukung penandaan (flagging) data yang dibatasi pemrosesannya.',
    evidenceRequired: false,
  },
  {
    id: 'sr-09',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 5',
    question: 'Apakah seluruh permintaan hak subjek data dicatat dalam log/register dengan status dan waktu penyelesaiannya?',
    weight: 2,
    options: likert(),
    hint: 'Register DSAR membuktikan pemenuhan hak atas informasi (Pasal 5) dan menjadi alat monitoring SLA. Tanpa pencatatan, organisasi tidak dapat membuktikan kepatuhan saat diaudit.',
    evidenceRequired: true,
  },
  {
    id: 'sr-10',
    domainId: 'subjectRights',
    pasalRef: 'Pasal 12',
    question: 'Apakah organisasi memiliki prosedur penanganan permintaan ganti rugi subjek data atas pelanggaran pemrosesan?',
    weight: 1,
    options: likert(),
    hint: 'Pasal 12 menjamin hak subjek data menggugat dan menerima ganti rugi atas pelanggaran pemrosesan. Prosedur internal mempercepat resolusi dan memitigasi risiko litigasi.',
    evidenceRequired: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 3 — KEAMANAN DATA (Pasal 35-42) — 10 pertanyaan
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'sec-01',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 35',
    question: 'Apakah data pribadi dienkripsi saat disimpan (at-rest) di seluruh database, storage, dan backup?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 35 mewajibkan pengendali menjaga keamanan data dari pemrosesan tidak sah. Enkripsi at-rest (mis. AES-256) adalah kontrol teknis fundamental yang juga memitigasi dampak kebocoran.',
    evidenceRequired: true,
  },
  {
    id: 'sec-02',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 35',
    question: 'Apakah data pribadi dienkripsi saat ditransmisikan (in-transit) baik internal maupun eksternal (TLS 1.2+)?',
    weight: 3,
    options: likert(),
    hint: 'Transmisi tanpa enkripsi memungkinkan intersepsi data. TLS 1.2+ untuk semua kanal — termasuk API internal dan transfer file — adalah baseline keamanan Pasal 35.',
    evidenceRequired: false,
  },
  {
    id: 'sec-03',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 36',
    question: 'Apakah diterapkan access control berbasis least-privilege dan manajemen identitas (IAM) untuk akses ke data pribadi?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 36 mewajibkan pengendali menjaga kerahasiaan data pribadi. RBAC/least-privilege, review akses berkala, dan MFA membatasi akses hanya pada personel yang berkepentingan.',
    evidenceRequired: true,
  },
  {
    id: 'sec-04',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 35 & 39',
    question: 'Apakah dilakukan penetration testing dan vulnerability assessment secara berkala (minimal tahunan) pada sistem yang memproses data pribadi?',
    weight: 2,
    options: likert(),
    hint: 'Keandalan sistem (Pasal 39) harus diverifikasi, bukan diasumsikan. Pentest tahunan dan VA berkala adalah praktik standar untuk membuktikan kontrol keamanan berfungsi.',
    evidenceRequired: true,
  },
  {
    id: 'sec-05',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 39',
    question: 'Apakah terdapat backup teruji dan disaster recovery plan untuk sistem yang memproses data pribadi?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 39 mewajibkan pengendali menjaga keandalan sistem dan mencegah gangguan. Backup yang diuji restore-nya dan DRP dengan RTO/RPO terdefinisi memastikan ketersediaan data.',
    evidenceRequired: true,
  },
  {
    id: 'sec-06',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 35 & 46',
    question: 'Apakah aktivitas akses dan pemrosesan data pribadi dimonitor melalui log terpusat/SIEM dengan alerting?',
    weight: 2,
    options: likert(),
    hint: 'Deteksi dini kegagalan pelindungan data (prasyarat notifikasi Pasal 46) membutuhkan log audit terpusat dan alerting. Tanpa monitoring, breach bisa tidak terdeteksi berbulan-bulan.',
    evidenceRequired: false,
  },
  {
    id: 'sec-07',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 35',
    question: 'Apakah API dan integrasi pihak ketiga yang memproses data pribadi diamankan (autentikasi, rate limiting, audit)?',
    weight: 2,
    options: likert(),
    hint: 'API adalah vektor kebocoran data modern yang paling umum. Autentikasi kuat (OAuth2/mTLS), otorisasi per-objek, dan audit trail wajib untuk semua endpoint yang menyentuh data pribadi.',
    evidenceRequired: false,
  },
  {
    id: 'sec-08',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 37',
    question: 'Apakah dilakukan pengawasan internal terhadap pihak yang terlibat dalam pemrosesan data pribadi di bawah kendali organisasi?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 37 mewajibkan pengendali melakukan pengawasan terhadap setiap pihak yang terlibat dalam pemrosesan di bawah kendalinya — termasuk karyawan, kontraktor, dan sistem internal.',
    evidenceRequired: false,
  },
  {
    id: 'sec-09',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 38',
    question: 'Apakah organisasi menerapkan langkah pencegahan agar data pribadi tidak diakses secara tidak sah (DLP, segmentasi jaringan, hardening)?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 38 mewajibkan pengendali mencegah data pribadi diakses secara tidak sah. Kontrol preventif berlapis: DLP, segmentasi jaringan, hardening server, dan endpoint protection.',
    evidenceRequired: false,
  },
  {
    id: 'sec-10',
    domainId: 'dataSecurity',
    pasalRef: 'Pasal 34',
    question: 'Apakah dilakukan Penilaian Dampak Pelindungan Data Pribadi (DPIA) untuk pemrosesan berisiko tinggi?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 34 mewajibkan DPIA untuk pemrosesan berisiko tinggi: pengambilan keputusan otomatis, data spesifik, pemrosesan skala besar, profiling, atau penggunaan teknologi baru.',
    evidenceRequired: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 4 — TRANSFER DATA & PROSESOR PIHAK KETIGA (Pasal 55-56) — 10
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'tp-01',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah dilakukan penilaian keamanan vendor (vendor security assessment) sebelum menunjuk prosesor data pihak ketiga?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 51 menegaskan tanggung jawab pengendali atas pemrosesan yang dilakukan prosesor. Due diligence keamanan sebelum kontrak adalah mitigasi utama risiko rantai pasok data.',
    evidenceRequired: true,
  },
  {
    id: 'tp-02',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah seluruh kontrak dengan prosesor data memuat klausul DPA (Data Processing Agreement) sesuai UU PDP?',
    weight: 3,
    options: likert(),
    hint: 'Pemrosesan oleh prosesor harus berdasarkan perintah tertulis pengendali. DPA mengikat prosesor pada kewajiban keamanan, kerahasiaan, sub-prosesor, dan notifikasi insiden.',
    evidenceRequired: true,
  },
  {
    id: 'tp-03',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 56',
    question: 'Apakah transfer data pribadi ke luar wilayah Indonesia memenuhi syarat Pasal 56 (tingkat pelindungan setara/setingkat atau persetujuan subjek data)?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 56: transfer lintas batas hanya boleh bila negara tujuan memiliki tingkat pelindungan setara atau lebih tinggi, terdapat pelindungan memadai yang mengikat, atau atas persetujuan subjek data.',
    evidenceRequired: true,
  },
  {
    id: 'tp-04',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah organisasi memelihara inventaris seluruh prosesor data pihak ketiga beserta kategori data yang diproses?',
    weight: 2,
    options: likert(),
    hint: 'Inventaris prosesor adalah perluasan RoPA: siapa memproses data apa, di mana, dan atas dasar kontrak apa. Tanpa ini, organisasi tidak dapat merespons insiden vendor secara cepat.',
    evidenceRequired: true,
  },
  {
    id: 'tp-05',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51 Ayat 5',
    question: 'Apakah dilakukan audit atau review berkala terhadap kepatuhan prosesor pihak ketiga?',
    weight: 2,
    options: likert(),
    hint: 'Penilaian saat onboarding tidak cukup — postur keamanan vendor berubah. Audit berkala (kuesioner tahunan, sertifikasi ISO 27001/SOC 2, atau on-site audit) memastikan kepatuhan berkelanjutan.',
    evidenceRequired: false,
  },
  {
    id: 'tp-06',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah penggunaan sub-prosesor oleh vendor memerlukan persetujuan tertulis organisasi terlebih dahulu?',
    weight: 2,
    options: likert(),
    hint: 'Rantai sub-prosesor yang tidak terkontrol memperluas permukaan risiko tanpa visibilitas. Klausul persetujuan sub-prosesor menjaga kendali pengendali atas seluruh rantai pemrosesan.',
    evidenceRequired: false,
  },
  {
    id: 'tp-07',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 55',
    question: 'Apakah transfer data antar pengendali di dalam wilayah Indonesia didasari perjanjian dan dasar pemrosesan yang sah?',
    weight: 1,
    options: likert(),
    hint: 'Pasal 55 mengatur serah terima data antar pengendali dalam negeri: penerima wajib memenuhi kewajiban pelindungan yang sama. Perjanjian berbagi data (data sharing agreement) adalah instrumennya.',
    evidenceRequired: false,
  },
  {
    id: 'tp-08',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah terdapat prosedur offboarding vendor yang memastikan pengembalian atau pemusnahan data pribadi saat kontrak berakhir?',
    weight: 2,
    options: likert(),
    hint: 'Data yang tertinggal di vendor setelah kontrak berakhir adalah liability tanpa kendali. Klausul return-or-destroy dengan berita acara pemusnahan menutup celah ini.',
    evidenceRequired: false,
  },
  {
    id: 'tp-09',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 51',
    question: 'Apakah kontrak vendor mewajibkan prosesor memberitahukan insiden keamanan kepada organisasi dalam jangka waktu tertentu?',
    weight: 2,
    options: likert(),
    hint: 'Kewajiban notifikasi 3x24 jam pengendali (Pasal 46) hanya bisa dipenuhi bila prosesor melaporkan insiden lebih cepat lagi. Klausul notifikasi vendor (mis. 24 jam) wajib ada di DPA.',
    evidenceRequired: false,
  },
  {
    id: 'tp-10',
    domainId: 'thirdParty',
    pasalRef: 'Pasal 56',
    question: 'Apakah organisasi memetakan lokasi geografis penyimpanan dan pemrosesan data oleh seluruh vendor cloud yang digunakan?',
    weight: 2,
    options: likert(),
    hint: 'Kepatuhan Pasal 56 mustahil tanpa mengetahui di negara mana data berada. Pemetaan region cloud (termasuk replikasi dan backup lintas region) adalah prasyarat penilaian transfer.',
    evidenceRequired: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 5 — PELAPORAN INSIDEN (Pasal 46-50) — 10 pertanyaan
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'ir-01',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46',
    question: 'Apakah terdapat prosedur deteksi dan klasifikasi insiden kegagalan pelindungan data pribadi?',
    weight: 3,
    options: likert(),
    hint: 'Pasal 46 mengatur kewajiban saat terjadi kegagalan pelindungan data. Tanpa kriteria klasifikasi (apa yang termasuk "kegagalan pelindungan data"), kewajiban notifikasi tidak dapat dipicu tepat waktu.',
    evidenceRequired: true,
  },
  {
    id: 'ir-02',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46 Ayat 1',
    question: 'Apakah organisasi mampu menyampaikan pemberitahuan tertulis kegagalan pelindungan data dalam 3x24 jam kepada subjek data dan lembaga?',
    weight: 3,
    options: likert([
      'Tidak ada prosedur notifikasi sama sekali.',
      'Prosedur draft ada, namun belum pernah diuji terhadap tenggat 3x24 jam.',
      'Prosedur berjalan, template notifikasi siap, belum diuji end-to-end.',
      'Prosedur teruji (tabletop/simulasi) konsisten memenuhi tenggat 3x24 jam.',
    ]),
    hint: 'Pasal 46 Ayat 1: dalam hal terjadi kegagalan pelindungan data pribadi, pengendali wajib menyampaikan pemberitahuan tertulis paling lambat 3x24 jam kepada subjek data dan lembaga.',
    evidenceRequired: true,
  },
  {
    id: 'ir-03',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46 Ayat 2',
    question: 'Apakah template notifikasi insiden memuat minimal: data yang terungkap, kapan dan bagaimana terungkap, serta upaya penanganan?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 46 Ayat 2 merinci isi minimum pemberitahuan: data pribadi yang terungkap, kapan dan bagaimana terungkapnya, serta upaya penanganan dan pemulihan oleh pengendali.',
    evidenceRequired: true,
  },
  {
    id: 'ir-04',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46 Ayat 3',
    question: 'Apakah terdapat kriteria dan prosedur untuk pengumuman publik insiden yang mengganggu pelayanan publik atau berdampak luas?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 46 Ayat 3: dalam hal tertentu, pengendali wajib memberitahukan kegagalan pelindungan data kepada masyarakat. Kriteria "hal tertentu" perlu dioperasionalkan dalam prosedur internal.',
    evidenceRequired: false,
  },
  {
    id: 'ir-05',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46',
    question: 'Apakah setiap insiden didokumentasikan dan ditindaklanjuti dengan post-incident review beserta rencana perbaikan?',
    weight: 2,
    options: likert(),
    hint: 'Register insiden dan post-incident review membuktikan akuntabilitas dan mencegah insiden berulang. Regulator umumnya meminta riwayat insiden saat investigasi.',
    evidenceRequired: true,
  },
  {
    id: 'ir-06',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46',
    question: 'Apakah dilakukan latihan/simulasi respon insiden data (tabletop exercise) secara berkala minimal setahun sekali?',
    weight: 2,
    options: likert(),
    hint: 'Tenggat 3x24 jam sangat ketat — tim yang belum pernah berlatih hampir pasti gagal memenuhinya. Tabletop exercise tahunan menguji eskalasi, pengambilan keputusan, dan komunikasi.',
    evidenceRequired: false,
  },
  {
    id: 'ir-07',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46',
    question: 'Apakah terdapat tim respon insiden (IRT/CSIRT) dengan peran, eskalasi, dan kontak darurat yang terdefinisi?',
    weight: 2,
    options: likert(),
    hint: 'Respon 3x24 jam membutuhkan kejelasan siapa memutuskan apa: incident commander, legal, komunikasi, teknis. Daftar kontak darurat harus selalu mutakhir.',
    evidenceRequired: false,
  },
  {
    id: 'ir-08',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46',
    question: 'Apakah alur pelaporan insiden internal memungkinkan karyawan melaporkan dugaan insiden dengan cepat dan tanpa hambatan?',
    weight: 1,
    options: likert(),
    hint: 'Banyak breach terdeteksi pertama kali oleh karyawan lini depan. Kanal pelaporan yang mudah (hotline, form, chat) dan budaya tanpa-menyalahkan mempercepat deteksi.',
    evidenceRequired: false,
  },
  {
    id: 'ir-09',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 46 & 51',
    question: 'Apakah insiden yang terjadi di prosesor pihak ketiga tercakup dalam prosedur respon insiden organisasi?',
    weight: 2,
    options: likert(),
    hint: 'Kewajiban notifikasi tetap melekat pada pengendali meski insiden terjadi di vendor. Playbook harus mencakup koordinasi vendor: pengumpulan fakta, forensik, dan komunikasi bersama.',
    evidenceRequired: false,
  },
  {
    id: 'ir-10',
    domainId: 'incidentReporting',
    pasalRef: 'Pasal 47-49',
    question: 'Apakah manajemen memahami konsekuensi sanksi administratif dan pidana atas kegagalan penanganan insiden data?',
    weight: 1,
    options: likert(),
    hint: 'UU PDP memuat sanksi administratif (peringatan, penghentian pemrosesan, denda hingga 2% pendapatan tahunan) dan pidana (Pasal 67-73). Kesadaran manajemen menentukan prioritas investasi.',
    evidenceRequired: false,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN 6 — PELATIHAN & KESADARAN (Pasal 43-45) — 10 pertanyaan
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'tr-01',
    domainId: 'training',
    pasalRef: 'Pasal 20 & 37',
    question: 'Apakah terdapat program pelatihan privasi dan pelindungan data pribadi wajib untuk seluruh karyawan?',
    weight: 3,
    options: likert(),
    hint: 'Kontrol teknis runtuh bila manusia tidak paham. Pelatihan privasi wajib tahunan untuk semua karyawan adalah baseline pengawasan internal (Pasal 37) yang diharapkan regulator.',
    evidenceRequired: true,
  },
  {
    id: 'tr-02',
    domainId: 'training',
    pasalRef: 'Pasal 37',
    question: 'Apakah tim yang menangani pemrosesan data pribadi (engineering, CS, HR, marketing) mendapat pelatihan khusus sesuai perannya?',
    weight: 2,
    options: likert(),
    hint: 'Risiko privasi berbeda per fungsi: engineer perlu privacy-by-design, CS perlu verifikasi DSAR, marketing perlu aturan consent. Pelatihan role-based jauh lebih efektif daripada materi generik.',
    evidenceRequired: false,
  },
  {
    id: 'tr-03',
    domainId: 'training',
    pasalRef: 'Pasal 20',
    question: 'Apakah dilakukan awareness campaign privasi secara berkala (poster, email, intranet, town hall)?',
    weight: 1,
    options: likert(),
    hint: 'Pelatihan tahunan cepat terlupakan. Kampanye kesadaran berkelanjutan menjaga privasi tetap top-of-mind dan membangun budaya pelindungan data.',
    evidenceRequired: false,
  },
  {
    id: 'tr-04',
    domainId: 'training',
    pasalRef: 'Pasal 37',
    question: 'Apakah pemahaman karyawan terhadap materi privasi diuji (kuis, phishing simulation, assessment) dan hasilnya ditindaklanjuti?',
    weight: 2,
    options: likert(),
    hint: 'Kehadiran pelatihan ≠ pemahaman. Pengujian (skor minimum kelulusan, simulasi phishing berkala) mengukur efektivitas dan mengidentifikasi karyawan yang butuh remedial.',
    evidenceRequired: false,
  },
  {
    id: 'tr-05',
    domainId: 'training',
    pasalRef: 'Pasal 20 & 37',
    question: 'Apakah onboarding karyawan baru mencakup modul privasi dan penandatanganan komitmen kerahasiaan data?',
    weight: 2,
    options: likert(),
    hint: 'Hari pertama adalah momen pembentukan kebiasaan. Modul privasi saat onboarding plus NDA/komitmen kerahasiaan memastikan tidak ada karyawan yang mengakses data tanpa bekal.',
    evidenceRequired: false,
  },
  {
    id: 'tr-06',
    domainId: 'training',
    pasalRef: 'Pasal 53-54',
    question: 'Apakah DPO dan tim privasi mendapatkan pelatihan/sertifikasi profesional berkelanjutan (CIPP, CIPM, atau setara)?',
    weight: 2,
    options: likert(),
    hint: 'Pasal 54 mensyaratkan pejabat pelindungan data ditunjuk berdasarkan kualitas profesional dan pengetahuan hukum pelindungan data. Sertifikasi dan pelatihan berkelanjutan memenuhi syarat ini.',
    evidenceRequired: false,
  },
  {
    id: 'tr-07',
    domainId: 'training',
    pasalRef: 'Pasal 37',
    question: 'Apakah penyelesaian pelatihan privasi dilacak dan dilaporkan ke manajemen (completion rate, skor)?',
    weight: 1,
    options: likert(),
    hint: 'Metrik pelatihan (tingkat penyelesaian, skor rata-rata, tren per departemen) memberi manajemen visibilitas dan menjadi bukti kepatuhan saat audit regulator.',
    evidenceRequired: false,
  },
  {
    id: 'tr-08',
    domainId: 'training',
    pasalRef: 'Pasal 20',
    question: 'Apakah materi pelatihan diperbarui mengikuti perubahan regulasi, insiden internal, dan tren ancaman terbaru?',
    weight: 1,
    options: likert(),
    hint: 'Materi usang menciptakan rasa aman palsu. Review materi tahunan — memasukkan peraturan pelaksana UU PDP terbaru dan pembelajaran dari insiden — menjaga relevansi program.',
    evidenceRequired: false,
  },
  {
    id: 'tr-09',
    domainId: 'training',
    pasalRef: 'Pasal 37',
    question: 'Apakah pihak ketiga yang bekerja di lingkungan organisasi (kontraktor, magang, outsource) juga menerima pelatihan privasi?',
    weight: 2,
    options: likert(),
    hint: 'Kontraktor dan tenaga outsource sering punya akses data yang sama dengan karyawan tetap namun luput dari program pelatihan. Cakupan pelatihan harus mengikuti akses, bukan status kepegawaian.',
    evidenceRequired: false,
  },
  {
    id: 'tr-10',
    domainId: 'training',
    pasalRef: 'Pasal 20',
    question: 'Apakah manajemen senior dan direksi mendapatkan briefing berkala tentang postur kepatuhan PDP organisasi?',
    weight: 2,
    options: likert(),
    hint: 'Akuntabilitas pelindungan data berada di level korporasi. Briefing berkala ke direksi (risk appetite, status remediasi, insiden) memastikan dukungan sumber daya dan tone-from-the-top.',
    evidenceRequired: false,
  },
];

export function getQuestionsByDomain(domainId: string): Question[] {
  return QUESTIONS.filter((q) => q.domainId === domainId);
}

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}
